name: unit-tests

on:
  push:
    branches:
      - v*
  pull_request:
    branches:
      - v*

jobs:
  build:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
        os: [ ubuntu-latest, macos-latest ]
        go: [ '1.13.x', '1.16.x' ]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: OS details
        run: |
          uname -a
          if [ -e /etc/os-release ]; then cat /etc/os-release; fi

      - name: Install packages
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get -y install krb5-user libkrb5-dev

      - name: Show environment
        run: env

      - name: Show GO environment
        run: go env

      - name: Install build tools
        run:  cd v2 && make tools

      - name: Check code formatting
        run: cd v2 && make fmtcheck

      - name: Linting
        run: cd v2 && make lint

      - name: Unit tests
        run: cd v2 && go test -race ./...

      - name: Make examples
        run: |
          which gcc
          which clang
          cd examples/go
          make -B
          cd ../c
          make -B


